 
 
const countries = [
    { name: "Afghanistan", code: "+93", capital: "Kabul" },
    { name: "Albania", code: "+355", capital: "Tirana" },
    { name: "Algeria", code: "+213", capital: "Algiers" },
    { name: "Andorra", code: "+376", capital: "Andorra la Vella" },
    { name: "Angola", code: "+244", capital: "Luanda" },
    { name: "Argentina", code: "+54", capital: "Buenos Aires" },
    { name: "Armenia", code: "+374", capital: "Yerevan" },
    { name: "Australia", code: "+61", capital: "Canberra" },
    { name: "Austria", code: "+43", capital: "Vienna" },
    { name: "Azerbaijan", code: "+994", capital: "Baku" },
    { name: "Bahamas", code: "+1-242", capital: "Nassau" },
    { name: "Bahrain", code: "+973", capital: "Manama" },
    { name: "Bangladesh", code: "+880", capital: "Dhaka" },
    { name: "Barbados", code: "+1-246", capital: "Bridgetown" },
    { name: "Belarus", code: "+375", capital: "Minsk" },
    { name: "Belgium", code: "+32", capital: "Brussels" },
    { name: "Belize", code: "+501", capital: "Belmopan" },
    { name: "Benin", code: "+229", capital: "Porto-Novo" },
    { name: "Bhutan", code: "+975", capital: "Thimphu" },
    { name: "Bolivia", code: "+591", capital: "Sucre" },
    { name: "Bosnia and Herzegovina", code: "+387", capital: "Sarajevo" },
    { name: "Botswana", code: "+267", capital: "Gaborone" },
    { name: "Brazil", code: "+55", capital: "Brasília" },
    { name: "Brunei", code: "+673", capital: "Bandar Seri Begawan" },
    { name: "Bulgaria", code: "+359", capital: "Sofia" },
    { name: "Burkina Faso", code: "+226", capital: "Ouagadougou" },
    { name: "Burundi", code: "+257", capital: "Gitega" },
    { name: "Cabo Verde", code: "+238", capital: "Praia" },
    { name: "Cambodia", code: "+855", capital: "Phnom Penh" },
    { name: "Cameroon", code: "+237", capital: "Yaoundé" },
    { name: "Canada", code: "+1", capital: "Ottawa" },
    { name: "Central African Republic", code: "+236", capital: "Bangui" },
    { name: "Chad", code: "+235", capital: "N'Djamena" },
    { name: "Chile", code: "+56", capital: "Santiago" },
    { name: "China", code: "+86", capital: "Beijing" },
    { name: "Colombia", code: "+57", capital: "Bogotá" },
    { name: "Comoros", code: "+269", capital: "Moroni" },
    { name: "Congo (Congo-Brazzaville)", code: "+242", capital: "Brazzaville" },
    { name: "Costa Rica", code: "+506", capital: "San José" },
    { name: "Croatia", code: "+385", capital: "Zagreb" },
    { name: "Cuba", code: "+53", capital: "Havana" },
    { name: "Cyprus", code: "+357", capital: "Nicosia" },
    { name: "Czech Republic", code: "+420", capital: "Prague" },
    { name: "Denmark", code: "+45", capital: "Copenhagen" },
    { name: "Djibouti", code: "+253", capital: "Djibouti" },
    { name: "Dominica", code: "+1-767", capital: "Roseau" },
    { name: "Dominican Republic", code: "+1-809", capital: "Santo Domingo" },
    { name: "East Timor (Timor-Leste)", code: "+670", capital: "Dili" },
    { name: "Ecuador", code: "+593", capital: "Quito" },
    { name: "Egypt", code: "+20", capital: "Cairo" },
  { name: "El Salvador", code: "+503", capital: "San Salvador" },
  { name: "Equatorial Guinea", code: "+240", capital: "Malabo" },
  { name: "Eritrea", code: "+291", capital: "Asmara" },
  { name: "Estonia", code: "+372", capital: "Tallinn" },
  { name: "Eswatini", code: "+268", capital: "Mbabane" },
  { name: "Ethiopia", code: "+251", capital: "Addis Ababa" },
  { name: "Fiji", code: "+679", capital: "Suva" },
  { name: "Finland", code: "+358", capital: "Helsinki" },
  { name: "France", code: "+33", capital: "Paris" },
  { name: "Gabon", code: "+241", capital: "Libreville" },
  { name: "Gambia", code: "+220", capital: "Banjul" },
  { name: "Georgia", code: "+995", capital: "Tbilisi" },
  { name: "Germany", code: "+49", capital: "Berlin" },
  { name: "Ghana", code: "+233", capital: "Accra" },
  { name: "Greece", code: "+30", capital: "Athens" },
  { name: "Grenada", code: "+1-473", capital: "St. George's" },
  { name: "Guatemala", code: "+502", capital: "Guatemala City" },
  { name: "Guinea", code: "+224", capital: "Conakry" },
  { name: "Guinea-Bissau", code: "+245", capital: "Bissau" },
  { name: "Guyana", code: "+592", capital: "Georgetown" },
  { name: "Haiti", code: "+509", capital: "Port-au-Prince" },
  { name: "Honduras", code: "+504", capital: "Tegucigalpa" },
  { name: "Hungary", code: "+36", capital: "Budapest" },
  { name: "Iceland", code: "+354", capital: "Reykjavik" },
  { name: "India", code: "+91", capital: "New Delhi" },
  { name: "Indonesia", code: "+62", capital: "Jakarta" },
  { name: "Iran", code: "+98", capital: "Tehran" },
  { name: "Iraq", code: "+964", capital: "Baghdad" },
  { name: "Ireland", code: "+353", capital: "Dublin" },
  { name: "Israel", code: "+972", capital: "Jerusalem" },
  { name: "Italy", code: "+39", capital: "Rome" },
  { name: "Jamaica", code: "+1-876", capital: "Kingston" },
  { name: "Japan", code: "+81", capital: "Tokyo" },
  { name: "Jordan", code: "+962", capital: "Amman" },
  { name: "Kazakhstan", code: "+7", capital: "Nur-Sultan" },
  { name: "Kenya", code: "+254", capital: "Nairobi" },
  { name: "Kiribati", code: "+686", capital: "South Tarawa" },
  { name: "Kuwait", code: "+965", capital: "Kuwait City" },
  { name: "Kyrgyzstan", code: "+996", capital: "Bishkek" },
  { name: "Laos", code: "+856", capital: "Vientiane" },
  { name: "Latvia", code: "+371", capital: "Riga" },
  { name: "Lebanon", code: "+961", capital: "Beirut" },
  { name: "Lesotho", code: "+266", capital: "Maseru" },
  { name: "Liberia", code: "+231", capital: "Monrovia" },
  { name: "Libya", code: "+218", capital: "Tripoli" },
  { name: "Liechtenstein", code: "+423", capital: "Vaduz" },
  { name: "Lithuania", code: "+370", capital: "Vilnius" },
  { name: "Luxembourg", code: "+352", capital: "Luxembourg" },
  { name: "Madagascar", code: "+261", capital: "Antananarivo" },
  { name: "Malawi", code: "+265", capital: "Lilongwe" },
  { name: "Malaysia", code: "+60", capital: "Kuala Lumpur" },
  { name: "Maldives", code: "+960", capital: "Malé" },
  { name: "Mali", code: "+223", capital: "Bamako" },
  { name: "Malta", code: "+356", capital: "Valletta" },
  { name: "Marshall Islands", code: "+692", capital: "Majuro" },
  { name: "Mauritania", code: "+222", capital: "Nouakchott" },
  { name: "Mauritius", code: "+230", capital: "Port Louis" },
  { name: "Mexico", code: "+52", capital: "Mexico City" },
  { name: "Micronesia", code: "+691", capital: "Palikir" },
  { name: "Moldova", code: "+373", capital: "Chișinău" },
  { name: "Monaco", code: "+377", capital: "Monaco" },
  { name: "Mongolia", code: "+976", capital: "Ulaanbaatar" },
  { name: "Montenegro", code: "+382", capital: "Podgorica" },
  { name: "Morocco", code: "+212", capital: "Rabat" },
  { name: "Mozambique", code: "+258", capital: "Maputo" },
  { name: "Myanmar", code: "+95", capital: "Naypyidaw" },
  { name: "Namibia", code: "+264", capital: "Windhoek" },
  { name: "Nauru", code: "+674", capital: "Yaren" },
  { name: "Nepal", code: "+977", capital: "Kathmandu" },
  { name: "Netherlands", code: "+31", capital: "Amsterdam" },
  { name: "New Zealand", code: "+64", capital: "Wellington" },
  { name: "Nicaragua", code: "+505", capital: "Managua" },
  { name: "Niger", code: "+227", capital: "Niamey" },
  { name: "Nigeria", code: "+234", capital: "Abuja" },
  { name: "North Macedonia", code: "+389", capital: "Skopje" },
  { name: "Norway", code: "+47", capital: "Oslo" },
  { name: "Oman", code: "+968", capital: "Muscat" },
  { name: "Pakistan", code: "+92", capital: "Islamabad" },
  { name: "Palau", code: "+680", capital: "Ngerulmud" },
  { name: "Panama", code: "+507", capital: "Panama City" },
  { name: "Papua New Guinea", code: "+675", capital: "Port Moresby" },
  { name: "Paraguay", code: "+595", capital: "Asunción" },
  { name: "Peru", code: "+51", capital: "Lima" },
  { name: "Philippines", code: "+63", capital: "Manila" },
  { name: "Poland", code: "+48", capital: "Warsaw" },
  { name: "Portugal", code: "+351", capital: "Lisbon" },
  { name: "Qatar", code: "+974", capital: "Doha" },
  { name: "Romania", code: "+40", capital: "Bucharest" },
  { name: "Russia", code: "+7", capital: "Moscow" },
  { name: "Rwanda", code: "+250", capital: "Kigali" },
  { name: "Saint Kitts and Nevis", code: "+1-869", capital: "Basseterre" },
  { name: "Saint Lucia", code: "+1-758", capital: "Castries" },
  { name: "Saint Vincent and the Grenadines", code: "+1-784", capital: "Kingstown" },
  { name: "Samoa", code: "+685", capital: "Apia" },
  { name: "San Marino", code: "+378", capital: "San Marino" },
  { name: "Sao Tome and Principe", code: "+239", capital: "São Tomé" },
  { name: "Saudi Arabia", code: "+966", capital: "Riyadh" },
  { name: "Senegal", code: "+221", capital: "Dakar" },
  { name: "Serbia", code: "+381", capital: "Belgrade" },
  { name: "Seychelles", code: "+248", capital: "Victoria" },
  { name: "Sierra Leone", code: "+232", capital: "Freetown" },
  { name: "Singapore", code: "+65", capital: "Singapore" },
  { name: "Slovakia", code: "+421", capital: "Bratislava" },
  { name: "Slovenia", code: "+386", capital: "Ljubljana" },
  { name: "Solomon Islands", code: "+677", capital: "Honiara" },
  { name: "Somalia", code: "+252", capital: "Mogadishu" },
  { name: "South Africa", code: "+27", capital: "Pretoria" },
  { name: "South Korea", code: "+82", capital: "Seoul" },
  { name: "South Sudan", code: "+211", capital: "Juba" },
  { name: "Spain", code: "+34", capital: "Madrid" },
  { name: "Sri Lanka", code: "+94", capital: "Colombo" },
  { name: "Sudan", code: "+249", capital: "Khartoum" },
  { name: "Suriname", code: "+597", capital: "Paramaribo" },
  { name: "Sweden", code: "+46", capital: "Stockholm" },
  { name: "Switzerland", code: "+41", capital: "Bern" },
  { name: "Syria", code: "+963", capital: "Damascus" },
  { name: "Taiwan", code: "+886", capital: "Taipei" },
  { name: "Tajikistan", code: "+992", capital: "Dushanbe" },
  { name: "Tanzania", code: "+255", capital: "Dodoma" },
  { name: "Thailand", code: "+66", capital: "Bangkok" },
  { name: "Togo", code: "+228", capital: "Lomé" },
  { name: "Tonga", code: "+676", capital: "Nukuʻalofa" },
  { name: "Trinidad and Tobago", code: "+1-868", capital: "Port of Spain" },
  { name: "Tunisia", code: "+216", capital: "Tunis" },
  { name: "Turkey", code: "+90", capital: "Ankara" },
  { name: "Turkmenistan", code: "+993", capital: "Ashgabat" },
  { name: "Tuvalu", code: "+688", capital: "Funafuti" },
  { name: "Uganda", code: "+256", capital: "Kampala" },
  { name: "Ukraine", code: "+380", capital: "Kyiv" },
  { name: "United Arab Emirates", code: "+971", capital: "Abu Dhabi" },
  { name: "United Kingdom", code: "+44", capital: "London" },
  { name: "United States", code: "+1", capital: "Washington, D.C." },
  { name: "Uruguay", code: "+598", capital: "Montevideo" },
  { name: "Uzbekistan", code: "+998", capital: "Tashkent" },
  { name: "Vanuatu", code: "+678", capital: "Port Vila" },
  { name: "Vatican City", code: "+379", capital: "Vatican City" },
  { name: "Venezuela", code: "+58", capital: "Caracas" },
  { name: "Vietnam", code: "+84", capital: "Hanoi" },
  { name: "Yemen", code: "+967", capital: "Sana'a" },
  { name: "Zambia", code: "+260", capital: "Lusaka" },
  { name: "Zimbabwe", code: "+263", capital: "Harare" }
  ];


  module.exports = {
    countries
  }
  